
"use client";
import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { CheckCircle2, XCircle, Filter, Clock, MessageSquare } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Textarea } from '@/components/ui/textarea'; // Assuming this is for LLM message for faculty, not admin.
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { format } from 'date-fns';

interface LeaveRequest {
  id: string;
  facultyName: string;
  facultyId: string;
  department: string;
  startDate: Date;
  endDate: Date;
  reason: string;
  status: 'Pending' | 'Approved' | 'Rejected'; // Status of the leave request
  requestedAt: Date;
  llmGeneratedMessage?: string; // Optional message generated by LLM for the faculty when applying
}

const initialLeaveRequests: LeaveRequest[] = [
  { id: 'LR001', facultyName: 'Dr. Eleanor Vance', facultyId: 'F001', department: 'Physics', startDate: new Date(2024, 7, 20), endDate: new Date(2024, 7, 22), reason: 'Personal emergency', status: 'Pending', requestedAt: new Date(2024, 7, 10, 9, 0) },
  { id: 'LR002', facultyName: 'Prof. Samuel Green', facultyId: 'F002', department: 'Mathematics', startDate: new Date(2024, 8, 1), endDate: new Date(2024, 8, 5), reason: 'Attending a conference', status: 'Approved', requestedAt: new Date(2024, 7, 5, 14, 30) },
  { id: 'LR003', facultyName: 'Dr. Olivia Chen', facultyId: 'F003', department: 'Computer Science', startDate: new Date(2024, 7, 25), endDate: new Date(2024, 7, 25), reason: 'Doctor\'s appointment', status: 'Pending', requestedAt: new Date(2024, 7, 12, 11, 15) },
  { id: 'LR004', facultyName: 'Dr. Eleanor Vance', facultyId: 'F001', department: 'Physics', startDate: new Date(2024, 9, 10), endDate: new Date(2024, 9, 12), reason: 'Family vacation', status: 'Rejected', requestedAt: new Date(2024, 7, 1, 16, 0) },
];

const departments = ["Physics", "Mathematics", "Computer Science", "All Departments"]; // For filtering

export default function LeaveRequestsPage() {
  const [leaveRequests, setLeaveRequests] = useState<LeaveRequest[]>(initialLeaveRequests);
  const [filteredRequests, setFilteredRequests] = useState<LeaveRequest[]>(leaveRequests);
  const [filterStatus, setFilterStatus] = useState<'Pending' | 'Approved' | 'Rejected' | 'All'>('Pending');
  const [filterDepartment, setFilterDepartment] = useState<string>('All Departments');

  const { toast } = useToast();

  useEffect(() => {
    let currentItems = leaveRequests;
    if (filterStatus !== 'All') {
      currentItems = currentItems.filter(req => req.status === filterStatus);
    }
    if (filterDepartment !== 'All Departments') {
      currentItems = currentItems.filter(req => req.department === filterDepartment);
    }
    // Sort by requestedAt date, newest first for pending, then by start date
    setFilteredRequests(currentItems.sort((a, b) => {
        if (a.status === 'Pending' && b.status !== 'Pending') return -1;
        if (a.status !== 'Pending' && b.status === 'Pending') return 1;
        if (a.status === 'Pending' && b.status === 'Pending') {
            return b.requestedAt.getTime() - a.requestedAt.getTime();
        }
        return a.startDate.getTime() - b.startDate.getTime();
    }));

  }, [leaveRequests, filterStatus, filterDepartment]);

  const handleUpdateRequestStatus = async (requestId: string, newStatus: 'Approved' | 'Rejected') => {
    // Simulate API call: await fetch(`/api/leaves/update/${requestId}`, { method: 'PATCH', body: JSON.stringify({ status: newStatus }) });
    setLeaveRequests(prevRequests =>
      prevRequests.map(req =>
        req.id === requestId ? { ...req, status: newStatus } : req
      )
    );
    toast({
      title: `Leave Request ${newStatus}`,
      description: `Request ID ${requestId} has been ${newStatus.toLowerCase()}.`,
      variant: newStatus === 'Approved' ? 'default' : 'destructive', // default is usually success-like
    });
  };

  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold tracking-tight flex items-center"><Clock className="mr-3 h-8 w-8 text-primary" /> Faculty Leave Requests</h1>

      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="flex items-center"><Filter className="mr-2 h-5 w-5"/> Filters</CardTitle>
          <CardDescription>Filter leave requests by status and department.</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col sm:flex-row gap-4">
          <div>
            <Label htmlFor="status-filter">Status</Label>
            <Select value={filterStatus} onValueChange={(value: 'Pending' | 'Approved' | 'Rejected' | 'All') => setFilterStatus(value)}>
              <SelectTrigger id="status-filter" className="w-full sm:w-[180px]">
                <SelectValue placeholder="Filter by Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="All">All Statuses</SelectItem>
                <SelectItem value="Pending">Pending</SelectItem>
                <SelectItem value="Approved">Approved</SelectItem>
                <SelectItem value="Rejected">Rejected</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label htmlFor="department-filter">Department</Label>
            <Select value={filterDepartment} onValueChange={setFilterDepartment}>
              <SelectTrigger id="department-filter" className="w-full sm:w-[220px]">
                <SelectValue placeholder="Filter by Department" />
              </SelectTrigger>
              <SelectContent>
                {departments.map(dept => (
                  <SelectItem key={dept} value={dept}>{dept}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {filteredRequests.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredRequests.map(request => (
            <Card key={request.id} className="shadow-md hover:shadow-lg transition-shadow">
              <CardHeader>
                <div className="flex justify-between items-start">
                    <div>
                        <CardTitle className="text-lg">{request.facultyName}</CardTitle>
                        <CardDescription>{request.department} - ID: {request.facultyId}</CardDescription>
                    </div>
                    <Badge variant={
                        request.status === 'Approved' ? 'default' :
                        request.status === 'Rejected' ? 'destructive' :
                        'secondary' // For Pending
                    }>
                        {request.status}
                    </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-2">
                <p className="text-sm"><strong>Dates:</strong> {format(request.startDate, "PP")} - {format(request.endDate, "PP")}</p>
                <p className="text-sm"><strong>Reason:</strong> {request.reason}</p>
                <p className="text-xs text-muted-foreground">Requested on: {format(request.requestedAt, "PPp")}</p>
                {request.llmGeneratedMessage && (
                    <details className="text-xs mt-1">
                        <summary className="cursor-pointer text-primary hover:underline">View LLM Message</summary>
                        <p className="p-2 border rounded bg-muted/50 mt-1">{request.llmGeneratedMessage}</p>
                    </details>
                )}
              </CardContent>
              {request.status === 'Pending' && (
                <CardFooter className="flex justify-end gap-2 border-t pt-4">
                  <AlertDialog>
                    <AlertDialogTrigger asChild>
                      <Button variant="outline" size="sm" className="text-red-600 border-red-600 hover:bg-red-50 hover:text-red-700">
                        <XCircle className="mr-2 h-4 w-4" /> Reject
                      </Button>
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                      <AlertDialogHeader>
                        <AlertDialogTitle>Confirm Rejection</AlertDialogTitle>
                        <AlertDialogDescription>
                          Are you sure you want to reject this leave request for {request.facultyName}?
                        </AlertDialogDescription>
                      </AlertDialogHeader>
                      <AlertDialogFooter>
                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                        <AlertDialogAction
                          onClick={() => handleUpdateRequestStatus(request.id, 'Rejected')}
                          className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                        >
                          Confirm Reject
                        </AlertDialogAction>
                      </AlertDialogFooter>
                    </AlertDialogContent>
                  </AlertDialog>
                  <AlertDialog>
                    <AlertDialogTrigger asChild>
                      <Button size="sm" className="bg-green-600 hover:bg-green-700 text-white">
                        <CheckCircle2 className="mr-2 h-4 w-4" /> Approve
                      </Button>
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                      <AlertDialogHeader>
                        <AlertDialogTitle>Confirm Approval</AlertDialogTitle>
                        <AlertDialogDescription>
                          Are you sure you want to approve this leave request for {request.facultyName}?
                        </AlertDialogDescription>
                      </AlertDialogHeader>
                      <AlertDialogFooter>
                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                        <AlertDialogAction 
                            onClick={() => handleUpdateRequestStatus(request.id, 'Approved')}
                            className="bg-primary text-primary-foreground hover:bg-primary/90"
                        >
                            Confirm Approve
                        </AlertDialogAction>
                      </AlertDialogFooter>
                    </AlertDialogContent>
                  </AlertDialog>
                </CardFooter>
              )}
            </Card>
          ))}
        </div>
      ) : (
        <Card>
          <CardContent className="py-12">
            <p className="text-center text-muted-foreground">No leave requests match the current filters.</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
